services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            array $defaultSender: { address: '%jacquesndl.mailer.sender_address%', name: '%jacquesndl.mailer.sender_name%' }

    Jacquesndl\MailerBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
